<header>
   <p  style='font-size:36px;font-family:Arial; color:#F0F0F0; background-color: #00233c; padding-left: 20pt; padding-top: 20pt;padding-bottom: 10pt; padding-right: 20pt;'>
       Use Case 5 - Price Prediction
  <br>
       <img id="teradata-logo" src="https://storage.googleapis.com/clearscape_analytics_demo_data/DEMO_Logo/teradata.svg" alt="Teradata" style="width: 125px; height: auto; margin-top: 20pt;">
    </p>
</header>

<h2>Overview</h2>
<p>This notebook demonstrates a complete workflow for predicting product prices using deep learning and deploying the model within a Teradata environment. The use case involves a dataset containing product IDs, textual descriptions, and corresponding prices. The key steps include:</p>

<p><b>Text Preprocessing:</b> Product descriptions are tokenized using Hugging Face's AutoTokenizer to prepare them for model input.</p>
<p><b>Model Training:</b> A PyTorch-based LSTM model is trained using tokenized descriptions and normalized price values.</p>
<p><b>Model Export:</b> The trained model is converted to ONNX format for scalable inference.</p>
<p><b>Teradata Integration:</b> The ONNX model is deployed using Teradata's ONNXPredict function to generate predictions on the test dataset.</p>
<p><b>Postprocessing:</b> Predictions are formatted using Teradata's Pack and ExtractValue functions. Prices are denormalized and tokens decoded to retrieve readable descriptions and predicted prices.</p>
<p><b>Benchmarking:</b> Execution times for key operations are recorded to evaluate performance.</p>

<p>This notebook serves as a practical example of combining NLP, deep learning, and Teradata's advanced analytics capabilities for real-world price prediction tasks.</p>

<h3>Sections:</h3>
<ol>
    <li>Import the required libraries</li>
    <li>Connect to the database</li>
    <li>View the initial table</li>
    <li>Split the data into train and test sets</li>
    <li>Create dataframes for the training and testing data</li>
    <li>Tokenize the data using HuggingFace model</li>
    <li>Create a dataframe for the tokenized test data and store it in the database</li>
    <li>Create the LSTM price prediction model using PyTorch</li>
    <li>Train the LSTM model on the training data</li>
    <li>Save the trained model in ONNX format</li>
    <li>Save the ONNX model to the database</li>
    <li>Run the ONNX model using ONNXPredict</li>
    <li>Format the results using in database functions</li>
    <li>View the formatted prediction results</li>
    <li>View Benchmark Analytics</li>
</ol>

<h3>1. Import the required libraries</h3>

In [1]:
# Import the required libraries
import settings
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer
import onnx
import numpy as np
import pandas as pd
import re
import time
from teradataml import create_context, DataFrame, copy_to_sql, remove_context, execute_sql

<h3>2. Connect to the database</h3>

In [2]:
# Connect to the database
create_context(host=settings.system_dsn, username=settings.system_user, password=settings.system_pw, logmech='LDAP')

Engine(teradatasql://jv255027:***@vantage24.td.teradata.com?LOGDATA=%2A%2A%2A&LOGMECH=%2A%2A%2A)

<h3>3. View the initial table</h3>

In [3]:
# View the initial table
marketplace_table = DataFrame.from_query("SELECT * FROM TPCXAI.marketplace;")
marketplace_table.head()

         price                                                                                                                                                                                                                                                                                                                        description
id
100      34.52  "by Guess Cute iPhone guess wallet phone case This phone case was used for less than week. Has adapter for headset jack and doesn't need screen cover as it has suction around the glass to keep water out. This is the authentic LuMee two case fit for your iPhone plus Please feel free to bundle. Message me if interested!!"
10000    87.82                                                                                                                                                                                                                                                                              "Deb Grey seamless French terry leggings Never worn."
100000   85.52                                                                                                                                                                                                                                           "Mezco Living dead Doll Demonique Not factory sealed but still in an alright condition."
10001   164.38                                                                                                                                                                                                                                                                          "The Limited Nude/ Gold bracelet Bought from the Limited"
10003    48.21                                                                                                                                                                                                                "Oakley OAKLEY oversized pullover size L, fits big, hangs off shoulder never been worn and doesn't have any Flaws."
10004    84.33                                                                                                                                                                                            "Vanity Vanity Cargo Jacket Worn twice. Doesn't have any signs of wear. Ask any questions. Usually ships same day. Purchase price 145-"
10002    28.39                                                                                                                                                  "Blair Tops 3x Tops sz 3x not worn. Washed once in machine in cold water, hung up to air dry but still it managed to shrink little bit heavier soft material and great condition"
1000    165.94                                                                                                                                                                                                                                                       "Dots Dots heels Cheetah print shoe heels W/ lace Size 10 Kimchi Blue brand"
10       95.05                                                                                                                                                                                                                                             "Disney Rain boots Cars rain boots size Stacked ankle boots. fit or 8! NOT FOREVER 21"
1        40.01                                                                                                                                                                                                            "Revlon BH cosmetics, revolution palette Only used handful of time, booty call is the only other one I've really used."

<h3>4. Split the data into train and test sets</h3>

In [5]:
# Split the data into training and testing sets
# Drop the table if it already exists
execute_sql("DROP TABLE TPCXAI.marketplace_train_test_split;")

# Save the time taken to split the data
split_data_start_time = time.time()

train_test_split_query = """
CREATE MULTISET TABLE TPCXAI.marketplace_train_test_split AS (
    SELECT * FROM TD_TrainTestSplit(
        ON TPCXAI.marketplace AS InputTable
        USING
        IDColumn('id')
        trainSize(0.8)
        testSize(0.2)
    ) as dt
) WITH DATA;
"""
execute_sql(train_test_split_query)

# Save the time taken to split the data
split_data_time = time.time() - split_data_start_time

In [6]:
# View the train_test_split table
train_test_split = DataFrame.from_query("SELECT * FROM TPCXAI.marketplace_train_test_split;")
train_test_split.head()

                  id   price                                                                                                                                                                                                                                                                                                                                                                                                                                        description
TD_IsTrainRow
0              21089   81.37                                                                                                                                                                                                                                                                                                "Esprit Flip-flops Flip-flops in great condition Please refer to all photos Offers welcome! Don't forget to check out my closet! bundle to save :)"
0              56534   54.37                                                                                                                                                                                                                                                                                   "VTech Vtech vSmile Games Cartridges games: includes Winnie the Pooh, Elmo, Alphabet, and Bratz. Smoke free home! Fast shipping! #gba, #gameboy, #games Krislyn"
0              15707   32.85                                                                                                                                                                                                                                                                 "Freya Gorgeous floral lace trim bra size 32G Floral. Black trim. Thicker, Adjustable straps. Not padded or push up but does have underwire. setting hook closure back. Size 32G."
0              70242   27.05                                                                                                                                                                                                                                                                                                                               "Express â¡Neck chain black express dress top Super cute forever 21 crotchet crop top! bought it but never wore :/"
0              71377  114.95                                                                                                                                                                                                                                                                                                                                            "Christina Rhinestone and pearl necklace set Christina collection rhinestone and pearl poodle. CUTE!!!"
0              23731   34.23                                                                                                                                                                                                                                                                                                                                                               "Russell Athletic Long sleeve T-shirt Only worn once. Washed per LuLa instructions."
0              30535   94.38                                                                                                                                                                                                                                                                                                                                                                              "LC Lauren Conrad Authentic suede fringe boots Gently used condition"
0              94971   65.04                                                                                                                                                                                                                                                        "Fila Women's 9.5 Fila shoes Good condition, only worn for few months and concluded that they were too small. Sold them. Bought these in 10 and they're too big for me, in great condition"
0              55393   37.88  "ENERGIE Energie* Tunic Sweatshirt- Cute and Comfortable! â ¢â ¢Soft, lightweight material â ¢â ¢3/4 sleeves â ¢â ¢Kangaroo pocket â ¢â ¢Wide neck, could be worn off shoulders â ¢â ¢Super cute when paired with leggings or some skinny jeans! (brown tunic has teensy tiny hole in the armpit where the tag was. It came to me like that. Only worn one time. It doesn't show any worn appearance at all. No piling and from smoke free home."
0              91146   95.01                                                                                                                                                                                    "H&M Size 7.5 H&M men Retail price 58.00 If any questions comment usually accept offers. Check out the rest of my items. I'd love to give discount for bundle purchases! TAGS: Nike, Under Armour, sneakers, running, fitness, athletic, like new, New Balance"

In [7]:
# Create separate train and test tables in the database
execute_sql("DROP TABLE TPCXAI.marketplace_train;")
execute_sql("DROP TABLE TPCXAI.marketplace_test;")

# Save the time taken to create train and test tables
split_tables_start_time = time.time()

execute_sql("CREATE MULTISET TABLE TPCXAI.marketplace_train AS (SELECT * FROM TPCXAI.marketplace_train_test_split WHERE TD_IsTrainRow = 1) WITH DATA;")
execute_sql("CREATE MULTISET TABLE TPCXAI.marketplace_test AS (SELECT * FROM TPCXAI.marketplace_train_test_split WHERE TD_IsTrainRow = 0) WITH DATA;")

# Save the time taken to create train and test tables
split_tables_time = time.time() - split_tables_start_time

<h3>5. Create dataframes for the training and testing data</h3>

In [8]:
# Import the dataset
#Load the data from the database
select_query = """SELECT id, description, CAST(price AS FLOAT) AS price FROM TPCXAI.marketplace_train;"""

#Execute the select query
df = DataFrame.from_query(select_query)

df = df.to_pandas()

#Find the min and max prices
min_price = df['price'].min()
max_price = df['price'].max()

#Clean the product descriptions
df['description'] = df['description'].fillna('')
df['price'] = (df['price'] - min_price) / (max_price - min_price)  # Normalize prices

In [ ]:
# Create a dataframe for the test set
#Load the data from the database
select_query = """SELECT id, description, CAST(price AS FLOAT) AS price FROM TPCXAI.marketplace_test;"""

#Execute the select query
test_df = DataFrame.from_query(select_query)

test_df = test_df.to_pandas()

#Find the min and max prices
min_price = test_df['price'].min()
max_price = test_df['price'].max()

#Clean the product descriptions
test_df['description'] = test_df['description'].fillna('')
test_df['price'] = (test_df['price'] - min_price) / (max_price - min_price)  # Normalize prices

<h3>6. Tokenize the textual descriptions data</h3>

In [10]:
# Tokenize the text
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
MAX_LEN = 100

class ProductDataset(Dataset):
    def __init__(self, dataframe):
        self.descriptions = dataframe['description'].tolist()
        self.prices = dataframe['price'].tolist()

    def __len__(self):
        return len(self.prices)
    
    def __getitem__(self, idx):
        tokens = tokenizer(
            self.descriptions[idx], 
            padding='max_length', 
            truncation=True, 
            max_length=MAX_LEN, 
            return_tensors="pt"
        )
        input_ids = tokens['input_ids'].squeeze(0)
        #print(input_ids.shape)
        attention_mask = tokens['attention_mask'].squeeze(0)
        price = torch.tensor(self.prices[idx], dtype=torch.float)
        return input_ids, attention_mask, price
    
dataset = ProductDataset(df)
test_dataset = ProductDataset(test_df)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=16, shuffle=False)

<h3>7. Create a dataframe to store the test data and store the test data into a table in the database</h3>

In [11]:
# Create a dataframe for the test data
all_input_ids = []
prices = []

for input_ids, _, price in test_dataset:
    all_input_ids.append(input_ids.tolist())
    prices.append(price.item())

# Combine input_ids and prices into a single list of rows
combined_data = [ids + [p] for ids, p in zip(all_input_ids, prices)]

# Create column names
columns = [f'input_ids_{i}' for i in range(len(all_input_ids[0]))] + ['price']

# Create DataFrame
df_input_ids = pd.DataFrame(combined_data, columns=columns)

# Display
print(df_input_ids.head())

   input_ids_0  input_ids_1  input_ids_2  input_ids_3  input_ids_4  \
0          101         1000         9423         8117        26126
1          101         1000        13528        13528         3963
2          101         1000         6373         6373         7708
3          101         1000        28517         2063        21602
4          101         1000         2004         2891         2235

   input_ids_5  input_ids_6  input_ids_7  input_ids_8  input_ids_9  ...  \
0         9423         8117        26126         9303        13548  ...
1         1005         1055         4330        24196        14523  ...
2        20345         4435         2047        17983         5245  ...
3         2099         1996        28517         2063        10086  ...
4        13610         2892        23684         4524         2235  ...

   input_ids_91  input_ids_92  input_ids_93  input_ids_94  input_ids_95  \
0          1010         26404          5898          3244         16195
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   input_ids_96  input_ids_97  input_ids_98  input_ids_99     price
0          1010          2570          1012           102  0.409674
1             0             0             0             0  0.115781
2             0             0             0             0  0.118165
3             0             0             0             0  0.059947
4             0             0             0             0  0.333150

[5 rows x 101 columns]

In [12]:
# Save the test data to a table in the database
td_test_df = DataFrame.from_pandas(df_input_ids)
td_test_df.to_sql('marketplace_test_input_ids', if_exists='replace')

In [13]:
# View the test data 
test_df_input = DataFrame.from_query("SELECT * FROM marketplace_test_input_ids;")
test_df_input.head()

   input_ids_0  input_ids_1  input_ids_2  input_ids_3  input_ids_4  input_ids_5  input_ids_6  input_ids_7  input_ids_8  input_ids_9  input_ids_10  input_ids_11  input_ids_12  input_ids_13  input_ids_14  input_ids_15  input_ids_16  input_ids_17  input_ids_18  input_ids_19  input_ids_20  input_ids_21  input_ids_22  input_ids_23  input_ids_24  input_ids_25  input_ids_26  input_ids_27  input_ids_28  input_ids_29  input_ids_30  input_ids_31  input_ids_32  input_ids_33  input_ids_34  input_ids_35  input_ids_36  input_ids_37  input_ids_38  input_ids_39  input_ids_40  input_ids_41  input_ids_42  input_ids_43  input_ids_44  input_ids_45  input_ids_46  input_ids_47  input_ids_48  input_ids_49  input_ids_50  input_ids_51  input_ids_52  input_ids_53  input_ids_54  input_ids_55  input_ids_56  input_ids_57  input_ids_58  input_ids_59  input_ids_60  input_ids_61  input_ids_62  input_ids_63  input_ids_64  input_ids_65  input_ids_66  input_ids_67  input_ids_68  input_ids_69  input_ids_70  input_ids_71  input_ids_72  input_ids_73  input_ids_74  input_ids_75  input_ids_76  input_ids_77  input_ids_78  input_ids_79  input_ids_80  input_ids_81  input_ids_82  input_ids_83  input_ids_84  input_ids_85  input_ids_86  input_ids_87  input_ids_88  input_ids_89  input_ids_90  input_ids_91  input_ids_92  input_ids_93  input_ids_94  input_ids_95  input_ids_96  input_ids_97  input_ids_98  input_ids_99     price  index_label
0          101         1000         5091         2538         2048         5091        17465         8722         2015         1006          9235          1007         18383          2892         23684          8722          2304          2892         23684          1998          5047          2938         15721          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.439713        15252
1          101         1000        24112         2072        17214        23692        10649         2072         2200         8217          2109         17214         23692         10649          2072          2007          2434          3482          2030          4981          1012          1037          1091          2483          2053          2489          7829          7829          3058          8137          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.087628        15255
2          101         1000        17053        17053         2093         7563         2098        13016        27212        17053          2093          7563          2098         13016         27212          9235          2005          1030         21161         10010         14074          2140          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.321103        15256
3          101         1000         7198         2303         2573         6396         2595         9530        21163        27396         13178          1010          2196          2109          1012          2069         25414          7690          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.057092        15257
4          101         1000        10725        10725         3165        16054        27212         1012         2047          999         10725          3165         16054         27212          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.147968        15259
5          101         1000         8459        24611         2047         9457         6879         1055         2480         1012          1021          1012          1019          2047          9457          6879          1055          2480          1012          1021          1012          1019          4518          2039          2006          2122          9874          2100          6879          2307          2005          2991          1013          3467          1010          2064          2022         10671          2091          2000          2191          7820          1012           999           999           999         24611          5091          4435          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.318956        15260
6          101         1000        10250         2072        10250         2401         9132         1055         2480         5396         13223         22751         10250          2401          9132          2946          6379          1013          5061          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.049969        15258
7          101         1000         1040         2243         4890         1040         2243         4890        10683         6007          2946          1040          2243          4890         10683          6007          2946          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.127488        15253
8          101         1000         2004         2271         2004         2271        16729        18866         3165         2023          3422          6719          2069          2038          2042          2109          2021          2009          1005          1055          1999          2204          4650          1998          2573          2307           999          2515          2031          2070          4929          2006          1996          7926          2087         18059          2015          2131          1010          1045          1005          1049          2330          2000          4107          1012          2911          2279          2154           999          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  0.747879        15251
9          101         1000        12062         3695         2849         7088        17697         2849         7088         2373          8313          4435          1024         17697          2849          7088          2433          1024          6381          6325          1024          2440          3103          3860          1024         11867          2546          2423          2828          1024          3192          2440          1011          6325          1010          6381          3192          2008          3640          5396          1011          2000          1011          2440          6325          2007          3096          1011          8295          6666          1012          1037         29647          2860         12707          2009          2515          1024          2507          2115         28838          1010          3019          1011          2559          6325          2007          2141          2023          2126          3192          1015          1012          1014         10258          6151         12870         23576          5396          1011          2000          1011          2440          6325          3192          1012         25567          1998          3514          1011          2489          1012          1012          1012          1012          3609          1024          3019         28799           102  0.032762        15249

<h3>8. Create the price prediction model using PyTorch</h3>

In [14]:
# Define the LSTM model
class PricePredictor(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=64):
        super(PricePredictor, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)

    def forward(self, input_ids, attention_mask):
        x = self.embedding(input_ids)
        _, (hn, _) = self.lstm(x)
        out = self.fc(hn.squeeze(0))
        return out.squeeze(1)
    
vocab_size = tokenizer.vocab_size
model = PricePredictor(vocab_size)

<h3>9. Train the LSTM price prediction model on the training data</h3>

In [15]:
# Save the time taken to train the model
train_model_start_time = time.time()

# Train the model
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0009)

for epoch in range(5):
    model.train()
    for input_ids, attention_mask, prices in dataloader:
        optimizer.zero_grad()
        outputs = model(input_ids, attention_mask)
        loss = criterion(outputs, prices)
        loss.backward()
        optimizer.step()
    if(epoch <= 0):
        torch.save((input_ids, attention_mask), 'sample_inputs.pt')
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

# Save the time taken to train the model
train_model_time = time.time() - train_model_start_time

Epoch 1, Loss: 0.012689820490777493
Epoch 2, Loss: 0.002635485725477338
Epoch 3, Loss: 0.0009854532545432448
Epoch 4, Loss: 0.000537659099791199
Epoch 5, Loss: 0.009093807078897953

<h3>10. Save the model in ONNX format</h3>

In [16]:
# Convert to onnx
input_ids, attention_mask = torch.load('sample_inputs.pt')

torch.onnx.export(
    model,
    (input_ids, attention_mask),
    "price_predictor.onnx",
    input_names=['input_ids', 'attention_mask'],
    output_names=['price'],
    dynamic_axes={'input_ids': {0: 'batch_size'}, 'attention_mask': {0: 'batch_size'}, 'price': {0: 'batch_size'}},
    opset_version=11
)

C:\Users\jv255027\AppData\Local\Temp\ipykernel_36344\373288960.py:4: DeprecationWarning: You are using the legacy TorchScript-based ONNX export. Starting in PyTorch 2.9, the new torch.export-based ONNX exporter will be the default. To switch now, set dynamo=True in torch.onnx.export. This new exporter supports features like exporting LLMs with DynamicCache. We encourage you to try it and share feedback to help improve the experience. Learn more about the new export logic: https://pytorch.org/docs/stable/onnx_dynamo.html. For exporting control flow: https://pytorch.org/tutorials/beginner/onnx/export_control_flow_model_to_onnx_tutorial.html.
  torch.onnx.export(
c:\Users\jv255027\AppData\Local\miniforge3\envs\UseCase5TorchEnv\Lib\site-packages\torch\onnx\symbolic_opset9.py:4244: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  warnings.warn(

<h3>11. Save the ONNX model to the database</h3>

In [17]:
#Start timer
load_model_start_time = time.time()

from teradataml import ONNXPredict, retrieve_byom, save_byom, configure
# Set BYOM install location
configure.byom_install_location = "mldb"

# Save the model path and name
model_path = 'price_predictor.onnx'
model_name = 'price_predictor'

#Drop the byom_models table if it exists
execute_sql("DROP TABLE byom_models;")

# Save the model to vantage
save_byom(model_name,
          model_file=model_path,
          table_name="byom_models")

#Save time
load_model_time = time.time() - load_model_start_time

Created the model table 'byom_models' as it does not exist.
Model is saved.

<h3>12. Run the LSTM model using ONNXPredict</h3>

In [18]:
# Start the timer
start_time = time.time()

# Run Onnx predict with the trained model
from teradataml import ONNXPredict, retrieve_byom, DataFrame
model_name = 'price_predictor'
#Run the predict function
result = ONNXPredict (
    accumulate = [f"input_ids_{i}" for i in range(100)],
    newdata=DataFrame.from_query("SELECT * FROM marketplace_test_input_ids"),
    modeldata=retrieve_byom(model_name, table_name="byom_models"),
    overwrite_cached_models="true",
    #show_model_input_fields_map = True,
    is_debug=True
)

# Save the time taken for prediction
prediction_time = time.time() - start_time

In [19]:
# View the initial results
print(result.result)

   input_ids_0  input_ids_1  input_ids_2  input_ids_3  input_ids_4  input_ids_5  input_ids_6  input_ids_7  input_ids_8  input_ids_9  input_ids_10  input_ids_11  input_ids_12  input_ids_13  input_ids_14  input_ids_15  input_ids_16  input_ids_17  input_ids_18  input_ids_19  input_ids_20  input_ids_21  input_ids_22  input_ids_23  input_ids_24  input_ids_25  input_ids_26  input_ids_27  input_ids_28  input_ids_29  input_ids_30  input_ids_31  input_ids_32  input_ids_33  input_ids_34  input_ids_35  input_ids_36  input_ids_37  input_ids_38  input_ids_39  input_ids_40  input_ids_41  input_ids_42  input_ids_43  input_ids_44  input_ids_45  input_ids_46  input_ids_47  input_ids_48  input_ids_49  input_ids_50  input_ids_51  input_ids_52  input_ids_53  input_ids_54  input_ids_55  input_ids_56  input_ids_57  input_ids_58  input_ids_59  input_ids_60  input_ids_61  input_ids_62  input_ids_63  input_ids_64  input_ids_65  input_ids_66  input_ids_67  input_ids_68  input_ids_69  input_ids_70  input_ids_71  input_ids_72  input_ids_73  input_ids_74  input_ids_75  input_ids_76  input_ids_77  input_ids_78  input_ids_79  input_ids_80  input_ids_81  input_ids_82  input_ids_83  input_ids_84  input_ids_85  input_ids_86  input_ids_87  input_ids_88  input_ids_89  input_ids_90  input_ids_91  input_ids_92  input_ids_93  input_ids_94  input_ids_95  input_ids_96  input_ids_97  input_ids_98  input_ids_99              json_report
0          101         1000         6874        21442        19562         2047          999         6874        21442        19562          3192         26018          3436          3435          1998          2489          2168          2154          7829          3310          1999          2049          2434          3482          2434          3976          1031         28549          1033          2205          4320          3539          2094          1998         18499         26741          2015          2035          2026         25536          5167          2024          4435          2047          2065          2025          2009          2097          2022          4415          3090          1012          5690          2005         21145          2000          2152          2203          4031          2061          2017          2097          2022          8534          1013          2988          1012          4283           999          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.04333944]}
1          101         1000         4569         9581         3508         2537         5202         3608         2541         2175          5283          3275          2541          2175          5283          2307          4650          4389         17651          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.074772395]}
2          101         1000         8958         5061         5061         2100        12922         4377         2066         2047          2946          5396          3376          2601          5061          6181          3091          4377          7732          2946          2312          2013          5904         18072          2063          1010          7683          2100         18178         28588         25336          2303          8663          4377          1012          4462          1010          5061          1010         22222          2304          1012          2047          2302         22073          1012          2946          2312          2021          2071          2036          4906          1060          2015          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.10886407]}
3          101         1000         7065         7811         2843         1997         2047         2191         2039        14012          1997          2047          1998         15171          2156         27263          2015          2005          4751          1012          1001         10550          4840         28799          2489          7829          1012          3976          3813          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.049732402]}
4          101         1000        11423         3384         2540         2192        16078         2196         2109         1010          2038          4677         16195          1012         15357          1010         19808         21041          7869          1010          8722          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0     {"price":[0.471811]}
5          101         1000        10636        16339         1060         2015         4539        10636        16339         4389          2015          4539         10636         16339          4435          1060          2015         11867         20051          3334          6773         27090          4190          4726          2015          2440          3091         18368          4013          4190          4726          2015          1010          2027          2024          3565          3730           999          2106          2424          2023          8313          2000          2448          2978          2006          1996          8154          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.11603987]}
6          101         1000         6986        23692         6200         2308         1005         1055         6986        23692          6200          4190          4726          2015          1012         22064          4140          2047          4190          4726          2015          1010          2069          6247          2320          1012          2946          1016          1012          3897          2304         14965          2316          1024          2946          2235          4190          4726          2806          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.11987583]}
7          101         1000         9298         2072         9298         2072        11591        23187         6267        14329          2946          5396          2307          4650          2069          6247          2028          2051          1998          1999          3819          4650           999           999          2069          4855          2138          2323          2031          2908          2039          2028          2946          1012          3565          9364          1012          2200         10140          2007          4190          4726          2015          1012          3730          4355          3430          1045          1005          2310          2412          2371          1012          2009          5683          6429          1012          2023          7027          2015          2012          1031         28549          1033          1012         22073          1024         11037          1010         10574          3401          1010         11037          6798         10294          1010         11037          2431         14101          1010          2431         14101          1010          1015          1013          1018         14101          1010          6598          1010          2665          1010          1000           102             0             0             0             0             0             0  {"price":[0.054031536]}
8          101         1000        20934        20473         2854         2308        15882         2196         2109         3165          5898          2745         12849          2869          6892          2275          7223          7485          4149          2005          1031         28549          1033          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0    {"price":[0.1695969]}
9          101         1000         5207        14722         5207         6007         2109        14722         5207        28130          1012          2946          1020          1012          1019          3360          1012          2204          4650          1010          2191          2019          3749           999          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.09937076]}

<h3>13. Format the results in database</h3>

<p>Save the results to a table in the database</p>

In [20]:
# Save the results to a table
result.result.to_sql("price_prediction_results", if_exists="replace")

In [21]:
# View results in table to validate
results_df = DataFrame.from_query("SELECT * FROM price_prediction_results")
results_df.head()

   input_ids_0  input_ids_1  input_ids_2  input_ids_3  input_ids_4  input_ids_5  input_ids_6  input_ids_7  input_ids_8  input_ids_9  input_ids_10  input_ids_11  input_ids_12  input_ids_13  input_ids_14  input_ids_15  input_ids_16  input_ids_17  input_ids_18  input_ids_19  input_ids_20  input_ids_21  input_ids_22  input_ids_23  input_ids_24  input_ids_25  input_ids_26  input_ids_27  input_ids_28  input_ids_29  input_ids_30  input_ids_31  input_ids_32  input_ids_33  input_ids_34  input_ids_35  input_ids_36  input_ids_37  input_ids_38  input_ids_39  input_ids_40  input_ids_41  input_ids_42  input_ids_43  input_ids_44  input_ids_45  input_ids_46  input_ids_47  input_ids_48  input_ids_49  input_ids_50  input_ids_51  input_ids_52  input_ids_53  input_ids_54  input_ids_55  input_ids_56  input_ids_57  input_ids_58  input_ids_59  input_ids_60  input_ids_61  input_ids_62  input_ids_63  input_ids_64  input_ids_65  input_ids_66  input_ids_67  input_ids_68  input_ids_69  input_ids_70  input_ids_71  input_ids_72  input_ids_73  input_ids_74  input_ids_75  input_ids_76  input_ids_77  input_ids_78  input_ids_79  input_ids_80  input_ids_81  input_ids_82  input_ids_83  input_ids_84  input_ids_85  input_ids_86  input_ids_87  input_ids_88  input_ids_89  input_ids_90  input_ids_91  input_ids_92  input_ids_93  input_ids_94  input_ids_95  input_ids_96  input_ids_97  input_ids_98  input_ids_99              json_report
0          101         1000        11808        14891        11808        14891        24829         2594         3540         2058          1996          6181          8925         26831          9573          4156          1999          2286          2005          5174          1002          1057         13871          2058          1996          6181          2030          6999          2058          1012          2308          1005          1055          2946          1023          1012          4435          2047          2196          2109          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0    {"price":[0.2488412]}
1          101         1000        21689        22885         9221        19688         3722        19688         2288         2083          1996         21689          3573         19511          2067          1012          9826          2065          2017          4965          2242          2842          2013          2026          3573          1010          1045          1005          1040          2022          5627          2000         13676          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0    {"price":[0.3700988]}
2          101         1000         3937         6572        14414         3797         1016         2595         2140         2047          2007          6415         10792         23115          4726          2003          3609          4462          3976          2003          3813         19575          2006         26825           999          2489          7829          2007          9651          1998          5427          1012          3813          3976          1012          2053         25416         26698          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.073487066]}
3          101         1000         2149        11037         4632         2078         2273         1005         1055         5396          6798         10294         11037          9829          2146         10353          3797          2007          4690          3869          3496          1998          5645          6536          2006         10353          1012          2038          2070          5061          2006          2067          1997         17170          1012          2273          2015          2946          2312          1012          4638          2041          2026         10328          2005          2060          2273          1005          1055          1056          1011          3797          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.042652488]}
4          101         1000         6175         6517         7432         6175         6517         7432         2460        10353          3797          1060         26212          3363          2204          4650          2053          8198         10973          2015         27094          2030          8198          1012          2307          4650          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.030043386]}
5          101         1000        11902         1005         7842        29656        11902         1005         1055        17983          3797          7683          2100         10040         24529         11961          2102          2428          4012         12031           999           999          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.03362201]}
6          101         1000         2577         2047         2308         1005         1055        20146         2312        18247          4003         10762          3205          2003          4435          2047          4003         10762          2013         18440         19894          9453          1012          1996          2067          2003          2936          2084          1996          2392          1998          2043          6247          2009          4472          2115         26352          1012          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.09502882]}
7          101         1000         6187         6895         4226         6187         6895         4226         3637         9132          2570          1013          2484         10140          6581          4650          6187          6895          4226          3637         16689          2011          4644         12471          4606          2946          2484         26762         13525          9132          4644         12471          2310          2638         12871         12038         26762         26450          2098         13525          9132          2946          2184          2137          6755         11018          7747          9132          2946          2021          3216          2312          1006          1045          4929          5373          1998          2122          4906          3819          2061          2027          2052          4906          2021          2453          2022          2210          4389          2006          2033          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0  {"price":[0.040818356]}
8          101         1000        10975        19736         2140        11972         3070         2005         4539         4368         11655          2998         10416          1998         13272          2275         15488          2050         29647          2023          2003          3848          3595          5061          6643          3900          2863          6471          2122          2024          1008          1008          1008          1008          2350          1008          1008          1008          1008          1998         17111          9541          2080          2524          2000          2424           999           999           999          5391          2000          2131         19394          2015          2006          2068           999          2191          2033          2019          3749           999          1008          2197          3861          3065         10120          1013         28629          2181          1008          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.09788957]}
9          101         1000         2474        27538         2417         5245         1011         2039        20345         2275          2417          6838         20345          2275          2946          1024          2235          4650          1024          6581          2065          5459          1031         28549          1033          2169          2053          2489          2911         14012          2000          3828          2006          7829          2050          1068          1037          1068         10814         11022          2022          2469          1997          2115          2946          2077          5309          2050          1068          1008          1008          4067          2017          2005          9361          2041          2026          9346          1012          3407          6023           999           999          1000           102             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0             0   {"price":[0.09255281]}

<p>Pack the token columns to one column that contains a list of tokens</p>

In [23]:
# Pack the columns in the results table
execute_sql("DROP TABLE price_prediction_results_packed;")
# Time to pack the results
pack_results_start_time = time.time()

pack_results_qry = """
CREATE TABLE price_prediction_results_packed AS (
SELECT * FROM Pack (
    ON price_prediction_results
    USING
    Delimiter(',')
    OutputColumn('tokenized_inputs')
    IncludeColumnName('false')
    TargetColumns('[0:99]')
    Accumulate('json_report')
) AS dt) WITH DATA;
"""

execute_sql(pack_results_qry)

# Save the time taken for packing results
pack_results_time = time.time() - pack_results_start_time

In [24]:
# View the packed results
packed_df = DataFrame.from_query("SELECT * FROM price_prediction_results_packed")
packed_df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  json_report
tokenized_inputs
101,1000,10017,3420,6379,1013,22088,10966,18901,4377,10017,3420,2601,6379,1013,22088,10966,18901,4377,1010,2946,1020,1012,3791,26035,2075,2004,3491,1012,2053,27094,2030,2878,2015,1012,3091,5761,2423,1000,1012,1037,24096,1013,6584,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                             {"price":[0.10970855]}
101,1000,10022,1053,1008,14324,2039,2005,5271,2003,6065,6100,1997,5722,1997,27838,15150,14256,3179,5860,2069,1012,5860,2003,1999,6581,4338,2247,2007,1996,11812,8288,1010,2288,2023,2502,11812,10930,6182,999,2307,3785,999,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                     {"price":[0.06970893]}
101,1000,10022,10930,6182,2466,1006,1050,21084,1007,2026,2214,10930,6182,2466,2006,1050,21084,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                                                 {"price":[0.05525834]}
101,1000,10022,11265,12881,2553,2005,7605,2015,11265,12881,8177,2005,16233,2304,1998,5061,7427,2441,2553,2003,2047,2196,2109,1008,2441,3482,1008,1008,18059,4606,1013,1020,2015,4606,3042,2553,2489,7829,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                               {"price":[0.037055343]}
101,1000,10022,13433,2912,29652,8202,3565,6547,16633,7605,2015,2208,4569,13433,2912,29652,8202,2208,2038,2042,7718,1998,2551,999,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                            {"price":[0.27718154]}
101,1000,10022,13528,13433,2912,29652,8202,17543,4979,9219,3081,2722,1012,1999,2204,4650,1012,2013,5610,2489,2188,3538,2275,23401,2050,1006,2053,6007,1007,3159,1012,1006,2748,6007,1007,2482,1006,4717,2884,2249,1007,22635,10658,2946,22388,5267,3436,24759,10732,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                           {"price":[0.10376482]}
101,1000,10022,11265,12881,2553,2005,7605,2015,11265,12881,8177,2005,16233,2304,1998,5061,7427,2441,2553,2003,2047,2196,2109,3310,2007,3898,16167,1998,2358,18871,1012,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                   {"price":[0.045455776]}
101,1000,10021,2316,2480,4583,1009,10021,2316,2480,14012,1997,10021,2316,2480,1012,2058,4583,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                                                  {"price":[0.11451046]}
101,1000,10017,3420,6379,1013,22088,10966,18901,4377,10017,3420,2601,6379,1013,22088,10966,18901,4377,1010,2946,1020,1012,2053,27094,2030,21407,18971,1012,2489,7094,2000,2618,4524,2007,5309,7208,2105,1996,3300,1010,14101,2015,2039,1996,2217,1012,26404,26666,19702,1012,6181,3091,1012,3504,2307,2007,2831,2304,6879,1012,14012,2000,3828,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                            {"price":[0.12573446]}
101,1000,10017,3420,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,6462,2039,2146,10353,3797,2946,1020,1012,2182,2024,2053,21407,1012,2009,2003,2978,12532,20186,2094,2021,2428,2025,17725,2127,2017,2024,2485,2039,2030,1999,3622,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0  {"price":[0.103486165]}

<p>Convert the JSON price predictions to a single float value</p>

In [26]:
# Convert the json_report to float
execute_sql("DROP TABLE price_prediction_results_float;")
# Save the time to convert json to float
json_to_float_start_time = time.time()

json_to_float_qry = """
CREATE TABLE price_prediction_results_float AS (
    SELECT 
        tokenized_inputs, 
        CAST(NEW JSON(json_report).JSONExtractValue('$..price[0]') AS FLOAT) AS price
FROM price_prediction_results_packed
) WITH DATA;
"""

execute_sql(json_to_float_qry)

# Save the time taken for converting json to float
json_to_float_time = time.time() - json_to_float_start_time

<p>Denormalize the price value</p>

In [27]:
# Denormalize the price value
execute_sql("DROP TABLE price_prediction_results_final;")
# Time to denormalize the price
denormalize_price_start_time = time.time()

denormalize_price_qry = """
CREATE TABLE price_prediction_results_final AS (
SELECT 
    tokenized_inputs, 
    price * (SELECT MAX(Price) - MIN(Price) FROM marketplace) + (SELECT MIN(Price) FROM marketplace) AS denormalized_price
FROM price_prediction_results_float
) WITH DATA;
"""
execute_sql(denormalize_price_qry)

# Save the time taken for denormalizing price
denormalize_price_time = time.time() - denormalize_price_start_time

In [28]:
# View the final results
final_df = DataFrame.from_query("SELECT * FROM price_prediction_results_final")
final_df.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      denormalized_price
tokenized_inputs
101,1000,10017,3420,6379,1013,22088,10966,18901,4377,10017,3420,2601,6379,1013,22088,10966,18901,4377,1010,2946,1020,1012,3791,26035,2075,2004,3491,1012,2053,27094,2030,2878,2015,1012,3091,5761,2423,1000,1012,1037,24096,1013,6584,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                     65.431666
101,1000,10022,1053,1008,14324,2039,2005,5271,2003,6065,6100,1997,5722,1997,27838,15150,14256,3179,5860,2069,1012,5860,2003,1999,6581,4338,2247,2007,1996,11812,8288,1010,2288,2023,2502,11812,10930,6182,999,2307,3785,999,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                             50.110611
101,1000,10022,10930,6182,2466,1006,1050,21084,1007,2026,2214,10930,6182,2466,2006,1050,21084,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                                                         44.575602
101,1000,10022,11265,12881,2553,2005,7605,2015,11265,12881,8177,2005,16233,2304,1998,5061,7427,2441,2553,2003,2047,2196,2109,1008,2441,3482,1008,1008,18059,4606,1013,1020,2015,4606,3042,2553,2489,7829,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                        37.603308
101,1000,10022,13433,2912,29652,8202,3565,6547,16633,7605,2015,2208,4569,13433,2912,29652,8202,2208,2038,2042,7718,1998,2551,999,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                                   129.578845
101,1000,10022,13528,13433,2912,29652,8202,17543,4979,9219,3081,2722,1012,1999,2204,4650,1012,2013,5610,2489,2188,3538,2275,23401,2050,1006,2053,6007,1007,3159,1012,1006,2748,6007,1007,2482,1006,4717,2884,2249,1007,22635,10658,2946,22388,5267,3436,24759,10732,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                   63.155039
101,1000,10022,11265,12881,2553,2005,7605,2015,11265,12881,8177,2005,16233,2304,1998,5061,7427,2441,2553,2003,2047,2196,2109,3310,2007,3898,16167,1998,2358,18871,1012,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                            40.820926
101,1000,10021,2316,2480,4583,1009,10021,2316,2480,14012,1997,10021,2316,2480,1012,2058,4583,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                                                                                                                                                                          67.270941
101,1000,10017,3420,6379,1013,22088,10966,18901,4377,10017,3420,2601,6379,1013,22088,10966,18901,4377,1010,2946,1020,1012,2053,27094,2030,21407,18971,1012,2489,7094,2000,2618,4524,2007,5309,7208,2105,1996,3300,1010,14101,2015,2039,1996,2217,1012,26404,26666,19702,1012,6181,3091,1012,3504,2307,2007,2831,2304,6879,1012,14012,2000,3828,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0                                                                                    71.570070
101,1000,10017,3420,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,10017,3420,2829,16240,6140,6462,2039,2146,10353,3797,2946,1020,1012,2182,2024,2053,21407,1012,2009,2003,2978,12532,20186,2094,2021,2428,2025,17725,2127,2017,2024,2485,2039,2030,1999,3622,1000,102,0,0,0,0,0,0,0,0,0,0,0,0,0           63.048306

In [ ]:
# Reverse the tokenization to get back the original product descriptions
final_df = final_df.to_pandas(index_column=None)
final_df.head()

                                                    denormalized_price
tokenized_inputs
101,1000,6578,6578,2146,10353,2304,12922,2039,2...           36.414876
101,1000,7592,14433,7592,14433,7518,6471,2946,2...           64.167843
101,1000,11572,5675,22936,3192,2109,2261,2335,2...           34.477800
101,1000,23951,10285,23951,10285,4338,16689,101...           35.139681
101,1000,2159,16102,5004,2159,16102,5004,2304,4...           48.253877

<h3>14. Denormalize the tokens and view the predictions</h3>

In [30]:
# Decode the tokens and view the final prediction
# Reset the index
final_df = final_df.reset_index()

# Decode the tokens back to text
decoded_texts = tokenizer.batch_decode(final_df['tokenized_inputs'].apply(lambda x: list(map(int, x.split(',')))).tolist(), skip_special_tokens=True)

# Save the decoded texts to the dataframe
final_df['ProductDescription'] = decoded_texts

# View the final dataframe
final_df.head()

,tokenized_inputs,denormalized_price,ProductDescription
0,"101,1000,6578,6578,2146,10353,2304,12922,2039,...",36.414876,""" gap gap long sleeve black lace up body suit ..."
1,"101,1000,7592,14433,7592,14433,7518,6471,2946,...",64.167843,""" hello kitty hello kitty sweat pants size no ..."
2,"101,1000,11572,5675,22936,3192,2109,2261,2335,...",34.477800,""" physicians formula cushion foundation used f..."
3,"101,1000,23951,10285,23951,10285,4338,16689,10...",35.139681,""" flexees flexees shapewear - 3x this is mediu..."
4,"101,1000,2159,16102,5004,2159,16102,5004,2304,...",48.253877,""" eyeshadow eyeshadow black dress size 12 worn..."

<h3>15. View the benchmark analytics</h3>

In [32]:
# View the benchmark times
print(f"Time to split data: ....................{split_data_time} seconds")
print(f"Time to create train and test tables: ..{split_tables_time} seconds")
print(f"Time to train model: ...................{train_model_time} seconds")
print(f"Time to load model: ....................{load_model_time} seconds")
print(f"Time for prediction: ...................{prediction_time} seconds")
print(f"Time for packing results: ..............{pack_results_time} seconds")
print(f"Time for converting json to float: .....{json_to_float_time} seconds")
print(f"Time for denormalizing price: ..........{denormalize_price_time} seconds")

Time to split data: ....................0.7335772514343262 seconds
Time to create train and test tables: ..1.7165658473968506 seconds
Time to train model: ...................2404.183906316757 seconds
Time to load model: ....................5.899831533432007 seconds
Time for prediction: ...................8.018739938735962 seconds
Time for packing results: ..............0.5518121719360352 seconds
Time for converting json to float: .....0.22649717330932617 seconds
Time for denormalizing price: ..........0.18636655807495117 seconds